
const V25_OFFERS=[
{airline:'Emirates',logo:'assets/airline-emirates.png',role:'First Officer',type:'Piloto',salary:28500,base:'Dubai (DXB)',aircraft:'A350-900',scale:'Internacional 6x3',rating:94,source:'Emirates Group Careers'},
{airline:'Emirates',logo:'assets/airline-emirates.png',role:'Cabin Crew',type:'Comissário',salary:12500,base:'Dubai (DXB)',aircraft:'A380 / B777 / A350',scale:'Internacional 5x2',rating:91,source:'Emirates Group Careers'},
{airline:'Emirates Engineering',logo:'assets/airline-emirates.png',role:'Licensed Aircraft Engineer',type:'Mecânico',salary:22000,base:'Dubai (DXB)',aircraft:'A380 / B777 / A350',scale:'Turnos 5x2',rating:93,source:'Emirates Group Careers'},
{airline:'Lufthansa City Airlines',logo:'assets/airline-lufthansa.png',role:'First Officer A220',type:'Piloto',salary:26000,base:'Frankfurt (FRA)',aircraft:'A220',scale:'Curto/médio curso',rating:92,source:'Lufthansa Group Careers'},
{airline:'Lufthansa',logo:'assets/airline-lufthansa.png',role:'Cabin Crew',type:'Comissário',salary:11500,base:'Frankfurt (FRA)',aircraft:'A320 / A350 / B787',scale:'Europeia + internacional',rating:88,source:'Lufthansa Group Careers'},
{airline:'Qatar Airways',logo:'assets/airline-qatar.png',role:'Captain',type:'Piloto',salary:33500,base:'Doha (DOH)',aircraft:'A350 / B777',scale:'Long-haul',rating:96,source:'Qatar Airways Careers'},
{airline:'TAP Air Portugal',logo:'assets/airline-tap.png',role:'First Officer',type:'Piloto',salary:19500,base:'Lisboa (LIS)',aircraft:'A320neo / A321LR',scale:'Europa + longo curso',rating:86,source:'TAP Careers'},
{airline:'LATAM',logo:'assets/airline-latam.png',role:'Comissário',type:'Comissário',salary:10500,base:'São Paulo (GRU)',aircraft:'A320 / B787 / B777',scale:'Regional + internacional',rating:84,source:'LATAM Careers'},
{airline:'Azul',logo:'assets/airline-azul.png',role:'Piloto',type:'Piloto',salary:17500,base:'Campinas (VCP)',aircraft:'A320neo / E195-E2',scale:'Brasil + internacional',rating:82,source:'Azul Carreiras'},
{airline:'GOL',logo:'assets/airline-gol.png',role:'Despachante Operacional',type:'Despachante',salary:9800,base:'São Paulo (GRU)',aircraft:'B737-800 / B737 MAX',scale:'Escala 6x2',rating:79,source:'GOL Carreiras'},
{airline:'British Airways',logo:'assets/airline-british.png',role:'First Officer',type:'Piloto',salary:27500,base:'London Heathrow (LHR)',aircraft:'A350 / B787 / B777',scale:'Long-haul',rating:90,source:'British Airways Careers'},
{airline:'United Airlines',logo:'assets/airline-united.png',role:'Mechanic',type:'Mecânico',salary:19000,base:'Newark (EWR)',aircraft:'B737 / B787 / B777',scale:'Turnos',rating:87,source:'United Careers'},
{airline:'Delta Air Lines',logo:'assets/airline-delta.png',role:'Flight Dispatcher',type:'Despachante',salary:16500,base:'Atlanta (ATL)',aircraft:'A330 / A350 / B767',scale:'24/7',rating:89,source:'Delta Careers'},
{airline:'RD AIRLINES',logo:'assets/rd-logo.png',role:'Comandante A350',type:'Piloto',salary:35000,base:'Resende (SDRS)',aircraft:'A350-900 / A350-1000',scale:'Internacional',rating:99,source:'RD AIRLINES — carreira virtual'}
];
function moneyV25(v){return 'R$ '+v.toLocaleString('pt-BR')+'/mês'}
function renderCareerOffersV25(){let el=document.getElementById('careerOffersGrid');if(!el)return;let t=document.getElementById('careerTypeV25')?.value||'Todos', q=(document.getElementById('careerSearchV25')?.value||'').toLowerCase();let arr=V25_OFFERS.filter(x=>(t==='Todos'||x.type===t)&&(!q||(x.airline+x.role+x.base+x.aircraft).toLowerCase().includes(q)));el.innerHTML=arr.map((x,i)=>`<article class="job-card"><div class="airline">✈ ${x.airline}</div><div class="role">${x.role}</div><span class="badge-v25">${x.type}</span><span class="badge-v25">⭐ ${x.rating}/100</span><div class="job-meta"><div>💰 <b>${moneyV25(x.salary)}</b></div><div>📍 <b>${x.base}</b></div><div>✈️ <b>${x.aircraft}</b></div><div>🕐 <b>${x.scale}</b></div></div><button onclick="applyCareerV25(${i})">Candidatar-se</button><div class="career-note">Oferta <b>virtual</b> inspirada em categorias de carreira da companhia. Não é uma vaga real.</div></article>`).join('')||'<p>Nenhuma oferta encontrada.</p>'}
function openCareerV25(){show('careerOffers');renderCareerOffersV25()}
function applyCareerV25(i){let t=document.getElementById('careerTypeV25')?.value||'Todos',q=(document.getElementById('careerSearchV25')?.value||'').toLowerCase();let arr=V25_OFFERS.filter(x=>(t==='Todos'||x.type===t)&&(!q||(x.airline+x.role+x.base+x.aircraft).toLowerCase().includes(q)));let x=arr[i];if(!x)return;let current=JSON.parse(localStorage.getItem('rdCareerV25')||'[]');current.push({...x,appliedAt:new Date().toISOString(),status:'Candidatura enviada'});localStorage.setItem('rdCareerV25',JSON.stringify(current));alert(`Candidatura enviada para ${x.airline}\n\nCargo: ${x.role}\nBase: ${x.base}\nSalário virtual: ${moneyV25(x.salary)}\n\nA contratação depende do resultado da simulação.`)}
