
const RD_AIRLINE_LOGOS_V22=[
['RD','RD AIRLINES','Brasil','Independente'],['RDP','RD AIRLINES-PORTUGAL','Europa','Independente'],
['G3','GOL Linhas Aéreas','Brasil','Independente'],['AD','Azul Linhas Aéreas','Brasil','Independente'],['LA','LATAM Airlines','América Latina','Independente'],['JJ','LATAM Brasil','Brasil','Independente'],
['AA','American Airlines','EUA/Canadá','oneworld'],['AS','Alaska Airlines','EUA/Canadá','oneworld'],['HA','Hawaiian Airlines','EUA/Canadá','oneworld'],['B6','JetBlue','EUA/Canadá','Independente'],['WN','Southwest Airlines','EUA/Canadá','Independente'],['UA','United Airlines','EUA/Canadá','Star Alliance'],['AC','Air Canada','EUA/Canadá','Star Alliance'],['WS','WestJet','EUA/Canadá','Independente'],['DL','Delta Air Lines','EUA/Canadá','SkyTeam'],
['BA','British Airways','Europa','oneworld'],['IB','Iberia','Europa','oneworld'],['AY','Finnair','Europa','oneworld'],['EI','Aer Lingus','Europa','oneworld'],['QR','Qatar Airways','Oriente Médio','oneworld'],['RJ','Royal Jordanian','Oriente Médio','oneworld'],['AT','Royal Air Maroc','África','oneworld'],
['LH','Lufthansa','Europa','Star Alliance'],['LX','SWISS','Europa','Star Alliance'],['OS','Austrian Airlines','Europa','Star Alliance'],['SN','Brussels Airlines','Europa','Star Alliance'],['SK','SAS','Europa','Star Alliance'],['TP','TAP Air Portugal','Europa','Star Alliance'],['TK','Turkish Airlines','Europa','Star Alliance'],['A3','Aegean Airlines','Europa','Star Alliance'],['LO','LOT Polish Airlines','Europa','Star Alliance'],['ET','Ethiopian Airlines','África','Star Alliance'],['MS','EgyptAir','África','Star Alliance'],['SA','South African Airways','África','Star Alliance'],
['AF','Air France','Europa','SkyTeam'],['KL','KLM','Europa','SkyTeam'],['AZ','ITA Airways','Europa','SkyTeam'],['UX','Air Europa','Europa','SkyTeam'],['SU','Aeroflot','Europa','Independente'],['RO','TAROM','Europa','SkyTeam'],
['EK','Emirates','Oriente Médio','Independente'],['EY','Etihad Airways','Oriente Médio','Independente'],['SV','Saudia','Oriente Médio','SkyTeam'],['WY','Oman Air','Oriente Médio','oneworld'],['GF','Gulf Air','Oriente Médio','Independente'],['FZ','flydubai','Oriente Médio','Independente'],
['SQ','Singapore Airlines','Ásia-Pacífico','Star Alliance'],['CX','Cathay Pacific','Ásia-Pacífico','oneworld'],['JL','Japan Airlines','Ásia-Pacífico','oneworld'],['NH','All Nippon Airways','Ásia-Pacífico','Star Alliance'],['QF','Qantas','Ásia-Pacífico','oneworld'],['MH','Malaysia Airlines','Ásia-Pacífico','oneworld'],['PR','Philippine Airlines','Ásia-Pacífico','Independente'],['TG','Thai Airways','Ásia-Pacífico','Star Alliance'],['KE','Korean Air','Ásia-Pacífico','SkyTeam'],['OZ','Asiana Airlines','Ásia-Pacífico','Star Alliance'],['CI','China Airlines','Ásia-Pacífico','SkyTeam'],['BR','EVA Air','Ásia-Pacífico','Star Alliance'],['CA','Air China','Ásia-Pacífico','Star Alliance'],['MU','China Eastern','Ásia-Pacífico','SkyTeam'],['CZ','China Southern','Ásia-Pacífico','SkyTeam'],['AI','Air India','Ásia-Pacífico','Star Alliance'],['6E','IndiGo','Ásia-Pacífico','Independente'],['NZ','Air New Zealand','Ásia-Pacífico','Star Alliance'],
['AM','Aeromexico','América Latina','SkyTeam'],['CM','Copa Airlines','América Latina','Star Alliance'],['AV','Avianca','América Latina','Star Alliance'],['H2','Sky Airline','América Latina','Independente'],['JA','JetSMART','América Latina','Independente'],['VB','Viva Aerobus','América Latina','Independente'],['Y4','Volaris','América Latina','Independente'],
['FR','Ryanair','Europa','Independente'],['U2','easyJet','Europa','Independente'],['W6','Wizz Air','Europa','Independente'],['TP','TAP Air Portugal','Europa','Star Alliance'],['FI','Icelandair','Europa','Independente'],['DY','Norwegian','Europa','Independente'],['VS','Virgin Atlantic','Europa','SkyTeam'],['VY','Vueling','Europa','Independente'],
['KQ','Kenya Airways','África','SkyTeam'],['WB','RwandAir','África','Star Alliance'],['AT','Royal Air Maroc','África','oneworld'],['MK','Air Mauritius','África','oneworld'],
['TS','Air Transat','EUA/Canadá','Independente'],['WS','WestJet','EUA/Canadá','Independente'],['FJ','Fiji Airways','Ásia-Pacífico','oneworld'],['VA','Virgin Australia','Ásia-Pacífico','Independente'],['QF','Qantas','Ásia-Pacífico','oneworld']
];
function airlineLogoV22(code){if(code==='RD'||code==='RDP')return 'assets/rd-logo.png';return 'https://images.kiwi.com/airlines/64/'+encodeURIComponent(code)+'.png';}
function renderAirlineLogosV22(){const grid=document.getElementById('airlineLogoGridV22');if(!grid)return;const q=(document.getElementById('airlineLogoSearchV22')?.value||'').toLowerCase();const reg=document.getElementById('airlineLogoRegionV22')?.value||'ALL';const ali=document.getElementById('airlineLogoAllianceV22')?.value||'ALL';const seen=new Set();const rows=RD_AIRLINE_LOGOS_V22.filter(x=>{const key=x[0];if(seen.has(key))return false;seen.add(key);return (reg==='ALL'||x[2]===reg)&&(ali==='ALL'||x[3]===ali)&&[x[0],x[1],x[2],x[3]].join(' ').toLowerCase().includes(q);});document.getElementById('airlineLogoCountV22').textContent=rows.length+' companhias no catálogo visual';grid.innerHTML=rows.map(x=>`<article class="airline-logo-card" onclick="document.getElementById('mapAirlineFilterV21').value='${x[0]}';show('map');renderRDMapV21()"><img class="airline-logo-img" src="${airlineLogoV22(x[0])}" onerror="this.onerror=null;this.src='assets/rd-logo.png'" alt="Logo ${x[1]}"><h4>${x[1]}</h4><small>${x[0]} • ${x[2]}</small></article>`).join('');}
document.addEventListener('DOMContentLoaded',renderAirlineLogosV22);
