
/* V24 — concorrência por passageiros + voos automáticos das companhias. */
const V24_HUBS={RD:['GRU','GIG','SDRS','REC'],RDP:['OPO'],G3:['GRU','GIG','REC'],AD:['VCP','CNF','REC'],LA:['GRU','SCL','LIM','BOG'],AA:['KDFW','KMIA','KJFK','KLAX'],UA:['KORD','KDEN','KSFO','KIAH'],DL:['KATL','KJFK','KMSP','KLAX'],EK:['OMDB','OMDW'],QR:['OTHH'],TP:['LPPR','LPPT','REC'],BA:['EGLL'],LH:['EDDF','EDDM'],AF:['LFPG','LFPO'],KL:['EHAM'],SQ:['WSSS'],CX:['VHHH'],JL:['RJAA'],NH:['RJTT'],QF:['YSSY'],ET:['HAAB'],SA:['FAOR'],AV:['SKBO'],CM:['MPTO'],AM:['MMMX'],FR:['EIDW'],U2:['EGLL'],W6:['LHBP'],TK:['LTFM'],AI:['VIDP'],AC:['CYYZ']};
const V24_PAIRS=[['GRU','OPO'],['GRU','LIS'],['GRU','SCL'],['GIG','MIA'],['REC','LIS'],['GRU','JFK'],['GRU','LAX'],['GRU','LIM'],['OPO','LIS'],['OPO','LHR'],['OPO','REC'],['OPO','CAI'],['JFK','LHR'],['LAX','NRT'],['DXB','LHR'],['DXB','GRU'],['DOH','LHR'],['DOH','GRU'],['CDG','JFK'],['FRA','JFK'],['AMS','JFK'],['SYD','LAX'],['SIN','NRT']];
let V24_STATE=JSON.parse(localStorage.getItem('rd_v24_competition')||'null');
function v24Name(code){let a=RD_AIRLINE_LOGOS_V22.find(x=>x[0]===code);return a?a[1]:code;}
function v24Logo(code){return (code==='RD'||code==='RDP')?'assets/rd-logo.png':'https://images.kiwi.com/airlines/64/'+encodeURIComponent(code)+'.png';}
function initV24(){if(V24_STATE)return;V24_STATE={flights:[],demand:{},stats:{}};let comps=RD_AIRLINE_LOGOS_V22.map(x=>x[0]).filter(c=>V24_HUBS[c]);comps.forEach((c,ci)=>{let hubs=V24_HUBS[c];for(let k=0;k<3;k++){let pair=V24_PAIRS[(ci*2+k)%V24_PAIRS.length];let o=hubs[k%hubs.length],d=pair[1];if(o===d)d=pair[0];V24_STATE.flights.push({id:c+'-V24-'+k,airline:c,flight:c+(1000+ci*10+k),origin:o,dest:d,model:v23Fleet(c)[k%v23Fleet(c).length],status:['Em voo','No solo','Chegando'][(ci+k)%3],passengers:Math.round(110+((ci*17+k*23)%170)),capacity:180+(k%2)*50});V24_STATE.stats[c]={passengers:0,flights:0,score:50+(ci%30)};}});saveV24();}
function saveV24(){localStorage.setItem('rd_v24_competition',JSON.stringify(V24_STATE));}
function tickV24(){initV24();V24_STATE.flights.forEach((f,i)=>{if(f.status==='No solo')f.status='Em voo';else if(f.status==='Em voo'&&i%3===0)f.status='Chegando';else if(f.status==='Chegando')f.status='No solo';let demand=120+Math.floor(Math.random()*170);f.passengers=Math.min(f.capacity,Math.max(35,demand+((f.airline==='RD'||f.airline==='RDP')?20:0)));let s=V24_STATE.stats[f.airline]||{passengers:0,flights:0,score:50};s.passengers+=f.passengers;s.flights+=1;s.score=Math.max(1,Math.min(99,Math.round(s.score+(f.passengers/f.capacity-.7)*2)));V24_STATE.stats[f.airline]=s;});V24_STATE.lastTick=new Date().toISOString();saveV24();if(document.getElementById('competition')&&document.getElementById('competition').style.display!=='none')renderCompetitionV24();}
function renderCompetitionV24(){initV24();let sel=document.getElementById('competitionAirlineV24'),status=document.getElementById('competitionStatusV24')?.value||'ALL',q=(document.getElementById('competitionSearchV24')?.value||'').toLowerCase();if(sel&&sel.options.length===1){RD_AIRLINE_LOGOS_V22.forEach(a=>{if(V24_HUBS[a[0]]){let o=document.createElement('option');o.value=a[0];o.textContent=a[1]+' ('+a[0]+')';sel.appendChild(o);}})}let al=sel?.value||'ALL';let rows=V24_STATE.flights.filter(f=>(al==='ALL'||f.airline===al)&&(status==='ALL'||f.status===status)&&[f.airline,f.flight,f.origin,f.dest,f.model].join(' ').toLowerCase().includes(q));let totalP=rows.reduce((n,f)=>n+f.passengers,0);let rdP=V24_STATE.flights.filter(f=>f.airline==='RD'||f.airline==='RDP').reduce((n,f)=>n+f.passengers,0);let compP=V24_STATE.flights.filter(f=>f.airline!=='RD'&&f.airline!=='RDP').reduce((n,f)=>n+f.passengers,0);let market=rdP+compP||1;document.getElementById('competitionSummaryV24').innerHTML='<div><b>'+rows.length+'</b><span>Voos exibidos</span></div><div><b>'+totalP.toLocaleString('pt-BR')+'</b><span>Passageiros nos voos</span></div><div><b>'+Math.round(rdP/market*100)+'%</b><span>Participação RD</span></div><div><b>'+Math.round(compP/market*100)+'%</b><span>Participação concorrentes</span></div>';
document.getElementById('competitorFlightsV24').innerHTML=rows.slice(0,80).map(f=>'<div class="competition-flight-v24"><div><img src="'+v24Logo(f.airline)+'" onerror="this.style.display=\'none\'" alt=""><b>'+v24Name(f.airline)+'</b><br><small>'+f.flight+' • '+f.model+'</small></div><div>📍 '+f.origin+' → '+f.dest+'</div><div class="competition-status-v24">● '+f.status+'</div><div>👥 '+f.passengers+'/'+f.capacity+'</div><div>📈 '+Math.round(f.passengers/f.capacity*100)+'% ocupação</div></div>').join('')||'<div class="card">Nenhum voo encontrado.</div>';
let demand=V24_PAIRS.slice(0,8).map((p,i)=>{let base=160+((i*41)%190),rd=Math.round(base*(.22+((i%3)*.04))),comp=base-rd;return '<div class="demand-v24"><b>'+p[0]+' → '+p[1]+'</b><strong>'+base+' passageiros</strong><small>RD AIRLINES: '+rd+' • concorrentes: '+comp+'</small></div>';}).join('');document.getElementById('passengerDemandV24').innerHTML=demand;
let ranking=Object.entries(V24_STATE.stats).sort((a,b)=>b[1].score-a[1].score).slice(0,20);document.getElementById('competitionRankingV24').innerHTML='<div class="ranking-v24"><b>#</b><b>Companhia</b><b>Passageiros</b><b>Índice</b></div>'+ranking.map((r,i)=>'<div class="ranking-v24"><span>'+(i+1)+'</span><span><b>'+v24Name(r[0])+'</b> ('+r[0]+')</span><span>'+r[1].passengers.toLocaleString('pt-BR')+'</span><span>'+Math.round(r[1].score)+'/100</span></div>').join('');}
setTimeout(()=>{initV24();setInterval(tickV24,20000);},2000);
